# Generated by Django 4.2.1 on 2023-06-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eating_Nutraceuticals',
            fields=[
                ('checking_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('nutraceuticals_name', models.CharField(max_length=100)),
                ('login_id', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'eating_nutraceuticals',
                'managed': True,
            },
        ),
    ]
