# Generated by Django 4.2.1 on 2023-06-15 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_login_id", models.CharField(max_length=100)),
                ("user_loing_password", models.CharField(max_length=100)),
                ("user_age", models.IntegerField()),
                ("user_name", models.CharField(max_length=100)),
                ("user_weight", models.FloatField(blank=True, null=True)),
                ("user_height", models.FloatField(blank=True, null=True)),
                ("user_nickname", models.CharField(max_length=100)),
                ("user_sex", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HealthInfo",
            fields=[
                ("health_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="account.user",
                    ),
                ),
            ],
            options={
                "db_table": "health_info",
                "managed": True,
            },
        ),
    ]
