# Generated by Django 4.2.2 on 2023-06-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_loing_password",
            new_name="user_login_password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_age",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
