# Generated by Django 4.2.1 on 2023-06-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="address",
            name="receiver",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
