# Generated by Django 4.2.1 on 2023-06-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthinfo",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
    ]
