# Generated by Django 4.2.1 on 2023-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_managers_alter_user_login_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthinfo",
            name="health_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
