# 베이스 이미지 설정
FROM node:latest

# set working directory
WORKDIR /app

# install dependencies
COPY ./front/package*.json . 

# install dependencies without copying node_modules directory
RUN yarn install --frozen-lockfile
# copy project files
COPY ./front .

RUN yarn format
RUN yarn install --check-files
# build Vue.js app
# RUN npm run build

CMD ["yarn", "dev"]
