# 베이스 이미지 설정
FROM node:latest

# set working directory
WORKDIR /app

# install dependencies
COPY ./front/package*.json . 

# install dependencies without copying node_modules directory
RUN npm install
# copy project files
COPY ./front .
# RUN npm run build

CMD ["npm", "run", "dev"]