# 베이스 이미지 설정
FROM node:18.16.0

# set working directory
WORKDIR /app

# install dependencies
COPY ./front/package*.json . 

# install dependencies without copying node_modules directory
RUN npm install
RUN npm install -g vite 
# copy project files
COPY ./front .
# RUN npm run build

CMD ["npm", "run", "dev"]