# Generated by Django 4.2.1 on 2023-06-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "company",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="new_Nutraceuticals",
            fields=[
                (
                    "input_number",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nutraceuticals_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("image", models.ImageField(upload_to="new_Nutraceuticals/")),
            ],
            options={
                "db_table": "new_nutraceuticals",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Nutraceuticals",
            fields=[
                (
                    "업체별_제품코드",
                    models.CharField(
                        default="미등록", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("업체코드", models.CharField(default="미등록", max_length=20)),
                ("제품코드", models.CharField(default="미등록", max_length=20)),
                ("nutraceuticals_name", models.CharField(max_length=100)),
                ("섭취시주의사항", models.TextField()),
                ("업소명", models.TextField()),
                ("섭취방법", models.TextField()),
                ("주된기능성", models.TextField()),
                ("유통기한", models.TextField()),
                ("보관방법", models.TextField()),
                ("원재료", models.TextField()),
                ("비타민D", models.FloatField(max_length=10)),
                ("비타민E", models.FloatField(max_length=10)),
                ("비타민k", models.FloatField(max_length=10)),
                ("비타민B1", models.FloatField(max_length=10)),
                ("비타민B2", models.FloatField(max_length=10)),
                ("나이아신", models.FloatField(max_length=10)),
                ("비타민B6", models.FloatField(max_length=10)),
                ("엽산", models.FloatField(max_length=10)),
                ("비타민B12", models.FloatField(max_length=10)),
                ("비오틴", models.FloatField(max_length=10)),
                ("비타민C", models.FloatField(max_length=10)),
                ("칼슘", models.FloatField(max_length=10)),
                ("마그네슘", models.FloatField(max_length=10)),
                ("철", models.FloatField(max_length=10)),
                ("아연", models.FloatField(max_length=10)),
                ("구리", models.FloatField(max_length=10)),
                ("셀레늄_셀렌", models.FloatField(max_length=10)),
                ("요오드", models.FloatField(max_length=10)),
                ("망간", models.FloatField(max_length=10)),
                ("몰리브덴", models.FloatField(max_length=10)),
                ("칼륨", models.FloatField(max_length=10)),
                ("식이섬유", models.FloatField(max_length=10)),
                ("단백질", models.FloatField(max_length=10)),
                ("프로바이오틱스", models.FloatField(max_length=10)),
                ("진세노사이드", models.FloatField(max_length=10)),
                ("루테인", models.FloatField(max_length=10)),
                ("EPA_DHA_Sum", models.FloatField(max_length=10)),
                ("비타민A", models.FloatField(max_length=10)),
            ],
            options={
                "db_table": "nutraceuticals",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "online_review_number",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nutraceuticals_name", models.CharField(max_length=100, unique=True)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("lowest", models.IntegerField()),
                ("reviews", models.TextField()),
                ("total_reviews", models.IntegerField()),
                ("average_rating", models.FloatField()),
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.nutraceuticals",
                    ),
                ),
            ],
            options={
                "db_table": "review",
                "managed": True,
            },
        ),
    ]
