# Generated by Django 4.2.1 on 2023-06-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutraceuticals',
            name='품목명',
            field=models.CharField(max_length=100),
        ),
    ]
