# Generated by Django 4.2.1 on 2023-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="nutraceuticals",
            name="nutraceuticals_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="onelinereview",
            name="online_review_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userreview",
            name="user_review_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
