# Generated by Django 4.2.1 on 2023-06-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutraceuticals',
            name='업체코드',
            field=models.IntegerField(default=0),
        ),
    ]
