# Generated by Django 4.2.1 on 2023-06-26 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0002_nutraceuticals_ad"),
    ]

    operations = [
        migrations.CreateModel(
            name="BareumReview",
            fields=[
                (
                    "bareum_review_number",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nutraceuticals_name", models.CharField(max_length=100, unique=True)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("reviews", models.TextField()),
                ("rating", models.FloatField()),
                ("review_img_url", models.ImageField(upload_to="review_images/")),
                (
                    "writer",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.nutraceuticals",
                    ),
                ),
            ],
            options={
                "db_table": "bareum_review",
                "managed": True,
            },
        ),
    ]
