# Generated by Django 4.2.1 on 2023-06-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_nutraceuticals_업체코드"),
    ]

    operations = [
        migrations.CreateModel(
            name="eating_Nutraceuticals",
            fields=[
                (
                    "checking_number",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nutraceuticals_name", models.CharField(max_length=100)),
                ("login_id", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "eating_nutraceuticals",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="new_Nutraceuticals",
            fields=[
                (
                    "input_number",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nutraceuticals_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("image", models.ImageField(upload_to="new_Nutraceuticals/")),
            ],
            options={
                "db_table": "new_nutraceuticals",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="nutraceuticals_name",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
