# Generated by Django 4.2.1 on 2023-06-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_nutraceuticals_품목명"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "online_review_number",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nutraceuticals_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("lowest", models.IntegerField()),
                ("reviews", models.TextField()),
                ("total_reviews", models.IntegerField()),
            ],
            options={
                "db_table": "review",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="OnelineReview",
        ),
        migrations.RenameField(
            model_name="nutraceuticals",
            old_name="품목명",
            new_name="nutraceuticals_name",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="베타카로틴",
        ),
        migrations.DeleteModel(
            name="UserReview",
        ),
    ]
