# Generated by Django 4.2.1 on 2023-06-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_eating_nutraceuticals_new_nutraceuticals_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eating_Nutraceuticals',
        ),
    ]
