# Generated by Django 4.2.1 on 2023-06-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_eating_nutraceuticals_new_nutraceuticals_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "online_review_number",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nutraceuticals_name", models.CharField(max_length=100, unique=True)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("lowest", models.IntegerField()),
                ("reviews", models.TextField()),
                ("total_reviews", models.IntegerField()),
            ],
            options={
                "db_table": "review",
                "managed": True,
            },
        ),
    ]
