# Generated by Django 4.2.1 on 2023-06-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_bareumreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bareumreview",
            name="review_img_url",
        ),
        migrations.AddField(
            model_name="nutraceuticals",
            name="bareum_certification",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nutraceuticals",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BareumReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_img_url", models.ImageField(upload_to="review_images/")),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.bareumreview",
                    ),
                ),
            ],
        ),
    ]
