# Generated by Django 4.2.1 on 2023-06-27 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_bareumreview_review_img_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bareumreview",
            name="post_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
