# Generated by Django 4.2.1 on 2023-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_bareumreview_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bareumreview",
            name="nutraceuticals_name",
            field=models.CharField(max_length=100),
        ),
    ]
