# Generated by Django 4.2.1 on 2023-06-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_bareumreview_nutraceuticals_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutraceuticals",
            name="click_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
