# Generated by Django 4.2.1 on 2023-06-26 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("post_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("post_title", models.CharField(max_length=100)),
                ("post_contents", models.CharField(max_length=100)),
                ("post_like", models.IntegerField()),
                ("post_category", models.CharField(max_length=9)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "post",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="post_images/")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="community.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("comments_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "comment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("comment_contents", models.CharField(max_length=100)),
                ("comment_like", models.IntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="community.comments",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="community.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comments",
                "managed": True,
            },
        ),
    ]
