# Generated by Django 4.2.1 on 2023-06-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                ("test_id", models.IntegerField(primary_key=True, serialize=False)),
                ("test_date", models.DateField()),
                ("test_contents", models.CharField(max_length=100)),
                ("test_like", models.IntegerField()),
            ],
            options={
                "db_table": "test",
                "managed": False,
            },
        ),
    ]
