# Generated by Django 4.2.1 on 2023-06-20 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_comments_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
