# Generated by Django 4.2.1 on 2023-06-20 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
