# Generated by Django 4.2.1 on 2023-06-29 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0006_alter_bareumreview_nutraceuticals_name"),
        ("account", "0002_address_phone_number_address_receiver"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularDelivery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "request_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("delivery_state", models.CharField(max_length=100)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.address",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.nutraceuticals",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "regular_delivery",
                "managed": True,
            },
        ),
    ]
