# 베이스 이미지 설정
FROM node:latest

# set working directory
WORKDIR /app

# install dependencies
COPY package*.json ./
RUN npm install

# copy project files
COPY . .

# build Vue.js app
# RUN npm run build
CMD ["npm", "run", "serve"]
